
name: silah
description: A new Flutter project.

publish_to: "none"

version: 3.0.6+3061

environment:
  sdk: ">3.0.2 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  animated_snack_bar: ^0.4.0
  animations: ^2.0.8
  better_player: 0.0.63
  cached_network_image: ^3.3.0
  camera: ^0.11.0
  carousel_slider: ^5.0.0
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.5
  custom_map_markers: ^0.0.2+1
  dio: ^5.1.2
  drag_down_to_pop: ^1.0.0
  equatable: ^2.0.5
  firebase_core: ^3.4.0
  firebase_database: ^11.1.1
  firebase_messaging: ^15.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_branch_sdk: ^8.2.0
  flutter_html: ^3.0.0-beta.1
  flutter_inset_box_shadow: ^1.0.8
  flutter_rating_bar: ^4.0.1
  flutter_ringtone_player: ^4.0.0+3
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  flutter_swipe_detector: ^2.0.0
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.4.0
  geolocator: ^12.0.0
  glassmorphism: ^3.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.2.8
  html: ^0.15.4
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.8
  images_picker: ^1.2.11
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  jiffy: ^6.1.0
  lottie: ^3.1.2
  media_cache_manager: ^0.2.2
  mobile_scanner: ^5.1.1
  path_provider: ^2.0.15
  permission_handler: ^11.3.1
  #  photo_manager: ^2.7.1
  pin_code_fields: ^8.0.1
  qr_code_tools: 
    path: C:/Users/Lenovo/Downloads/qr_code_tools-master/qr_code_tools-master
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  readmore: ^3.0.0
  scanly: ^0.0.3
  screenshot: 2.5.0
  shared_preferences: ^2.1.1
  story_view: ^0.16.5
  url_launcher: ^6.2.5
  video_player: ^2.7.0
  widget_zoom: ^0.0.3
  flutter_debouncer: ^2.0.0
  device_info_plus: ^8.2.2
  carousel_slider_plus: ^7.0.0
dependency_overrides:
  photo_manager: ^3.0.0-dev.2
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo-bg.png"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf

  assets:
    - assets/images/
    - assets/icons/
