
name: silah
description: A new Flutter project.

publish_to: "none"
  
version: 3.0.6+3061

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  # Http Client
  dio: ^5.1.2
  # State Management
  flutter_bloc: ^8.1.3
  # Animation
  animate_do: ^3.0.2
  lottie: ^3.1.2
  flutter_spinkit: ^5.2.0
  # TextField for pin code
  pin_code_fields: ^8.0.1
  # Awesome Icons
  font_awesome_flutter: ^10.4.0
  # Flutter Toast
  fluttertoast: ^8.2.2
  # Permission Handler
  permission_handler: ^11.3.1
  # For Launching Phones, Links etc
  url_launcher: ^6.1.11
  # For Copying Texts to Clipboard
  clipboard: ^0.1.3
  # Displaying HTML
  flutter_html: ^3.0.0-beta.1
  # For picking images from gallery or camera
  #  image_picker: ^0.8.5+3
  images_picker: 
    git:
      url: https://github.com/SamyMohammad/images_picker.git
  # Carousel Slider
  carousel_slider: ^5.0.0
  #shared pref
  shared_preferences: ^2.1.1
  # Geo Locator
  geolocator: ^12.0.0
  # Video Player
  better_player: ^0.0.83
  #  flick_video_player:
  #  video_player: ^2.3.0
  # Google maps
  google_maps_flutter: ^2.2.8
  # Generating QR Code
  qr_flutter: ^4.1.0
  # Scan QR Code
  qr_code_scanner: ^1.0.1
  # Rating Bar
  flutter_rating_bar: ^4.0.1
  # Inner shadow effect
  flutter_inset_box_shadow: ^1.0.8
  # Read more text functionality:
  readmore: ^3.0.0
  # Open hero animation
  animations: ^2.0.8
  # Firebase
  firebase_messaging: ^15.1.0
  firebase_core: ^3.4.0
  firebase_database: ^11.1.1
  flutter_swipe_detector: ^2.0.0
  scanly: ^0.0.3
  zxing2: any
  flutter_regex: ^0.0.3
  image_picker: 1.0.8
  zoom_pinch_overlay: ^1.4.3
  pretty_dio_logger: any
dependency_overrides:
  photo_manager: ^3.0.0-dev.2  
  custom_map_markers: ^0.0.2+1
  media_cache_manager: any
  intl: ^0.19.0
  jiffy: ^6.1.0
  flutter_ringtone_player: ^4.0.0+3
  path_provider: ^2.0.15
  widget_zoom: ^0.0.3

  camera: ^0.11.0+2
  video_player: ^2.7.0
  animated_snack_bar: ^0.4.0
  # photo_manager: ^2.7.1
  cached_network_image: ^3.3.0    
  flutter_svg: ^2.0.9
  flutter_branch_sdk: any
  device_info_plus: any
  carousel_slider_plus: any
  equatable: any
  infinite_scroll_pagination: any
  flutter_debouncer: any
  photo_view: ^0.15.0

  # image_gallery_saver: any
  screenshot: any
  drag_down_to_pop: any
  zxing2: any
  qr_code_tools: 
    path: C:/Users/Lenovo/Downloads/qr_code_tools-master/qr_code_tools-master
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo-bg.png"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf

  assets:
    - assets/images/
    - assets/icons/
